image: ubuntu:16.04

before_script:
  - apt-get update
  - apt-get install -y python3 python3-tk build-essential python3-pip nodejs npm curl git
  - npm install -g n
  - n stable
  - cd ..
  # - pip3 install --upgrade pip
  - git clone https://github.com/ReNom-dev-team/ReNom.git
  - cd ReNom
  - pip3 install -r requirements.txt
  - pip3 install -e .
  - cd ..
  - pip3 install wheel
  - pip3 install -r requirements.txt
  - pip install -e .

pages:
  script:
    - python3 setup.py bdist_wheel sdist
    - mkdir -p public/bin
    - cp dist/* public/bin
    - ls public/bin

  artifacts:
    paths:
    - public

# flake8:
#   script:
#     - flake8 .

pytest:
  script:
    - py.test
