image : node:9.8

before_script:
  - apt-get update -qq && apt-get install -y -qq python3 python3-pip python3-wheel pandoc
  - pip install -r requirements.txt
  - pip install -e .

flake8:
  script:
    - flake8 .

pytest:
  script:
    - export RENOM_PRECISION=64
    - py.test
    - export RENOM_PRECISION=32
    - py.test


pages:
  script:
    - python3 setup.py bdist_wheel sdist
    - mkdir -p public/bin
    - cp dist/* public/bin
    - ls public/bin

  artifacts:
    paths:
      - public
