image: node:10.1

before_script:
  - apt -y update && apt-get install -y tk-dev
  - wget https://www.python.org/ftp/python/3.5.0/Python-3.5.0.tar.xz
  - tar Jxfv Python-3.5.0.tar.xz
  - cd Python-3.5.0
  - ./configure; make; make install
  - alias python3='python3.5'; alias pip3='pip3.5'
  - cd ..
  - pip3 install --upgrade pip
  - pip3 install wheel
  - pip3 install -r requirements.txt
  - pip install -e .

# flake8:
#   script:
#     - flake8 .
#
# pytest:
#   script:
#     - export RENOM_PRECISION=64
#     - py.test
#     - export RENOM_PRECISION=32
#     - py.test

pages:
  script:
    - python3 setup.py bdist_wheel sdist
    - mkdir -p public/bin
    - cp dist/* public/bin
    - ls public/bin

  artifacts:
    paths:
    - public
